version: "3"

services:
  redis:
    image: redis:alpine3.16
    ports:
      - "6379:6379"
    networks:
      - backend

  api:
    build:
      context: .
    ports:
      - "8000:3000"
    volumes:
      - ./:/app
    networks:
      - backend


networks:
  backend:
